
import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { User, Song, UserRole, ViewState, UserSettings } from './types';
import { SetList } from './types';
import { MOCK_USER, MOCK_SONGS } from './constants';
import { dbService } from './services/dbService';
import { geminiService } from './services/geminiService';
import { storageService } from './services/storageService';
import SongViewer from './components/SongViewer';
import SongForm from './components/SongForm';
import SettingsView from './components/SettingsView';
import SetlistManager from './components/SetlistManager';
import SongNavigator from './components/SongNavigator';
import { useTheme } from './hooks/useTheme';
import RecentSongsView from './components/RecentSongsView';
import AdminDashboard from './components/AdminDashboard';
import { useAuth } from './hooks/useAuth';
import { useSongs } from './hooks/useSong';
import { useSetlists } from './hooks/useSetlists';
import { useTranspose, getKeyLabel } from './hooks/useTranspose';
import { Header } from './components/Header';
import { SongList } from './components/SongList';
import { useSongSearch } from './hooks/useSongSearch';
import { useNavigation } from './hooks/useNavigation';
// The 'virtual:pwa-register/react' module is generated by vite-plugin-pwa
import { useRegisterSW } from 'virtual:pwa-register/react'; 
import UpdatePrompt from './components/UpdatePrompt';
import OfflineReadyToast from './components/OfflineReadyToast';
import { getShouldUseFlats, transposeChord } from './utils/musicUtils';

const getRelativeTime = (timestamp: number) => {
  const diffInSeconds = Math.floor((Date.now() - timestamp) / 1000);
  if (diffInSeconds < 60) return 'Just now';
  const diffInMinutes = Math.floor(diffInSeconds / 60);
  if (diffInMinutes < 60) return `${diffInMinutes} minute${diffInMinutes !== 1 ? 's' : ''} ago`;
  const diffInHours = Math.floor(diffInMinutes / 60);
  if (diffInHours < 24) return `${diffInHours} hour${diffInHours !== 1 ? 's' : ''} ago`;
  const diffInDays = Math.floor(diffInHours / 24);
  return `${diffInDays} day${diffInDays !== 1 ? 's' : ''} ago`;
};

const TimeAgo: React.FC<{ timestamp: number }> = ({ timestamp }) => {
  const [, setTick] = useState(0);
  useEffect(() => {
    const interval = setInterval(() => setTick(t => t + 1), 60000);
    return () => clearInterval(interval);
  }, []);
  return <>{getRelativeTime(timestamp)}</>;
};

const normalizeUrlPart = (str: string) => {
  if (!str) return '';
  // This function creates a URL-friendly "slug" from a string.
  // It's improved to handle non-English characters with diacritics.
  const normalized = str // e.g., "L'été à Besançon"
    .toLowerCase()
    .replace(/ß/g, 'ss') // Handle German Eszett
    .replace(/æ/g, 'ae') // Handle ligatures
    .replace(/œ/g, 'oe')
    .normalize('NFD') // Decompose characters: "l'ete a besancon" + combining marks
    .replace(/[\u0300-\u036f]/g, '') // Remove diacritical marks
    .replace(/[^a-z0-9]+/g, '-') // Replace non-alphanumeric chars with hyphens
    .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
  
  if (normalized.length <= 10) return normalized;
  return normalized.substring(0, 10).replace(/-+$/, '');
};

const App: React.FC = () => {
  const { 
    user, 
    showEmailForm, setShowEmailForm,
    email, setEmail,
    password, setPassword,
    isSignUp, setIsSignUp,
    authError,
    resetSent,
    verificationSent,
    handleEmailAuth,
    handleGoogleLogin,
    handleLogout,
    handlePasswordReset,
    handleUpdateSettings
  } = useAuth();

  const {
    allSongs,
    currentSong,
    selectSong,
    handleSearch,
    saveSong,
    deleteSong,
    deleteSpecificSong,
    refreshSongs
  } = useSongs(user);

  const { searchQuery, setSearchQuery, filteredSongs, sortOrder, sortDirection, handleSortChange } = useSongSearch(allSongs);

  // PWA update and offline handling
  const [offlineReady, setOfflineReady] = useState(false);
  const [needRefresh, setNeedRefresh] = useState(false);
  
  const { updateServiceWorker } = useRegisterSW({
    onRegistered() {
      console.log('Service Worker registered.');
      setOfflineReady(true);
    },
    onRegisterError(error) {
      console.error('Service Worker registration error:', error);
    },
    onNeedRefresh() {
      setNeedRefresh(true);
    },
  });

  // Auto-dismiss the "Offline Ready" toast after 5 seconds
  useEffect(() => {
    if (offlineReady) {
      const timer = setTimeout(() => setOfflineReady(false), 5000);
      return () => clearTimeout(timer);
    }
  }, [offlineReady, setOfflineReady]);


  const [songToEdit, setSongToEdit] = useState<Song | undefined>(undefined);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [recentlyViewed, setRecentlyViewed] = useState<Song[]>([]);
  const [recentlyPlayedSetlists, setRecentlyPlayedSetlists] = useState<SetList[]>([]);
  const [isRouteHandled, setIsRouteHandled] = useState(false);
  const [localShowChords, setLocalShowChords] = useState(user?.settings.showChords ?? true);
  const transposeHandledRef = useRef<string>('');
  
  const [isSyncing, setIsSyncing] = useState(false);
  const [lastSyncTime, setLastSyncTime] = useState<number | null>(null);
  const [showSyncSuccess, setShowSyncSuccess] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem('cloudsong_last_synced');
    if (stored) {
      setLastSyncTime(parseInt(stored, 10));
    }
  }, []);

  // Auto-dismiss sync success toast
  useEffect(() => {
    if (showSyncSuccess) {
      const timer = setTimeout(() => setShowSyncSuccess(false), 4000);
      return () => clearTimeout(timer);
    }
  }, [showSyncSuccess]);

  // Create Setlist from Search State
  const [showCreateSetlistModal, setShowCreateSetlistModal] = useState(false);
  const [songsForSetlist, setSongsForSetlist] = useState<Song[]>([]);
  const [newSetlistName, setNewSetlistName] = useState('');
  const [editSetlistImmediately, setEditSetlistImmediately] = useState(true);
  const [targetSetlistId, setTargetSetlistId] = useState<string | null>(null); // Kept in App.tsx
  const [isHeaderSearchActive, setIsHeaderSearchActive] = useState(false); // Kept in App.tsx
  const [selectedIndex, setSelectedIndex] = useState(-1); // Kept in App.tsx
  const [pinnedSearchQuery, setPinnedSearchQuery] = useState<string>('');

  const recentSongs = useMemo(() => {
    return [...allSongs]
      .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0))
      .slice(0, 50);
  }, [allSongs]);

  // Sync session-level chord visibility with user settings on login, but not after.
  useEffect(() => {
    if (user) {
      setLocalShowChords(user.settings.showChords);
    }
  }, [user?.id]); // Only run when user ID changes (i.e., on login/logout)

  const handleSelectSong = useCallback(async (songId: string) => {
    if (hasUnsavedChanges) {
      if (!window.confirm('You have unsaved changes. Are you sure you want to discard them?')) return null;
      setHasUnsavedChanges(false);
    }
    const song = await selectSong(songId);
    if (song) {
      setView('SONG_VIEW');
      setSearchQuery('');
      setIsHeaderSearchActive(false);
      return song;
    }
    return null;
  }, [selectSong, hasUnsavedChanges]);

  const {
    setlists,
    activeSetlist,
    activeSetlistIndex,
    saveSetlist,
    deleteSetlist,
    playSetlist,
    navigateSetlist,
    exitSetlist,
    refreshSetlists
  } = useSetlists(user, handleSelectSong);

  // Add active setlist to recently played cache whenever it changes
  useEffect(() => {
    if (activeSetlist && user) {
      dbService.addToRecentSetlistsCache(user.id, activeSetlist);
    }
  }, [activeSetlist, user]);

  // Use the new navigation hook
  const {
    view,
    setView,
    menuOpen,
    setMenuOpen,
    showRecentlyViewedSubMenu,
    setShowRecentlyViewedSubMenu,
    showRecentlyPlayedSetlistsSubMenu,
    setShowRecentlyPlayedSetlistsSubMenu,
    cameFromAdminSongSearch,
    setCameFromAdminSongSearch,
    adminSetlistFilter,
    setAdminSetlistFilter,
    handleNavigation,
    handleAdminNavigate,
  } = useNavigation({
    hasUnsavedChanges, setHasUnsavedChanges, setSearchQuery, setIsHeaderSearchActive, setSelectedIndex, setSongToEdit, setTargetSetlistId, exitSetlist
  });

  // --- URL Routing & Deep Linking ---
  
  // 1. Sync URL with App State
  useEffect(() => {
    if (!isRouteHandled) return;
    let path = '/';
    if (view === 'SETTINGS') {
      path = '/settings';
    } else if (view === 'ADMIN_DASHBOARD') {
      path = '/admin';
    } else if (view === 'SETLIST_MANAGER') {
      path = '/setlists';
    } else if (view === 'RECENT_SONGS') {
      path = '/recent';
    } else if (view === 'SONG_VIEW' && currentSong) {
      if (activeSetlist) {
        // New robust URL for a song within a setlist with slug
        const setlistSlug = normalizeUrlPart(activeSetlist.name);
        const setlistPart = setlistSlug ? `${activeSetlist.id}-${setlistSlug}` : activeSetlist.id;
        path = `/setlist/${setlistPart}/${activeSetlistIndex}`;
      } else {
        // New robust URL for a standalone song with slug
        const songSlug = normalizeUrlPart(currentSong.title);
        const songPart = songSlug ? `${currentSong.id}-${songSlug}` : currentSong.id;
        path = `/song/${songPart}`;
      }
    }

    // Only push if different to avoid duplicate history entries
    if (window.location.pathname !== path) {
      window.history.pushState({ view, songId: currentSong?.id, setlistId: activeSetlist?.id, setlistIndex: activeSetlistIndex }, '', path);
    }
  }, [view, currentSong, activeSetlist, activeSetlistIndex, isRouteHandled]);

  // 2. Handle Browser Navigation (Back/Forward) and Initial Load
  useEffect(() => {
    const handleRoute = async () => {
      // Wait for data to be ready
      const pathSegments = window.location.pathname.substring(1).split('/');
      const isSetlistRoute = pathSegments[0] === 'setlist' && pathSegments.length >= 2;
      if (allSongs.length === 0 || (isSetlistRoute && setlists.length === 0)) {
        return;
      }

      const path = window.location.pathname.substring(1);
      if (!path) {
        if (view !== 'SONG_VIEW') setView('SONG_VIEW'); // Default to home
        return;
      }

      const parts = path.split('/').map(p => decodeURIComponent(p));
      const [route, idParam, indexStr] = parts;

      // Handle new, robust routing scheme
      switch (route) {
        case 'settings': setView('SETTINGS'); return;
        case 'admin': setView('ADMIN_DASHBOARD'); return;
        case 'setlists': setView('SETLIST_MANAGER'); return;
        case 'recent': setView('RECENT_SONGS'); return;
        case 'song':
          if (idParam) {
            const songMatch = allSongs.find(s => idParam === s.id || idParam.startsWith(s.id + '-'));
            if (songMatch) {
              await selectSong(songMatch.id);
              exitSetlist();
              setView('SONG_VIEW');
            } else {
              console.warn(`Song with ID param "${idParam}" not found.`);
            }
          }
          return;
        case 'setlist':
          if (idParam && indexStr) {
            const setlistMatch = setlists.find(s => idParam === s.id || idParam.startsWith(s.id + '-'));
            const index = parseInt(indexStr, 10);
            if (setlistMatch && !isNaN(index) && index >= 0 && index < setlistMatch.choices.length) {
              await playSetlist(setlistMatch, index);
              setView('SONG_VIEW');
            } else {
              console.warn(`Setlist (param: ${idParam}) or index (${indexStr}) is invalid.`);
            }
          }
          return;
      }
    };

    window.addEventListener('popstate', handleRoute);

    // Update initial load logic to use new route format
    const pathSegments = window.location.pathname.substring(1).split('/');
    const isSetlistRoute = pathSegments[0] === 'setlist';
    const setlistsReady = !isSetlistRoute || setlists.length > 0;

    if (!isRouteHandled && allSongs.length > 0 && setlistsReady) {
      handleRoute().finally(() => setIsRouteHandled(true));
    }

    return () => window.removeEventListener('popstate', handleRoute);
  }, [allSongs, setlists, playSetlist, selectSong, exitSetlist, isRouteHandled]);

  // Reset selection when search query changes
  useEffect(() => {
    // If search is cleared and it was initiated from the admin dashboard, go back.
    if (searchQuery === '' && cameFromAdminSongSearch) {
      setView('ADMIN_DASHBOARD');
      setCameFromAdminSongSearch(false);
    }
    setSelectedIndex(-1);
  }, [searchQuery, cameFromAdminSongSearch, setCameFromAdminSongSearch]);

  const handleUserSongSelect = async (songId: string) => { // already async
    setCameFromAdminSongSearch(false); // When a song is selected, we are done with the admin-initiated search.
    if (activeSetlist) {
      const index = activeSetlist.choices.findIndex(c => c.songId === songId);
      if (index !== -1) {
        await navigateSetlist(index);
      } else {
        const result = await handleSelectSong(songId);
        if (result) {
          exitSetlist();
        }
      }
    } else {
      await handleSelectSong(songId);
    }
    setMenuOpen(false);
    setShowRecentlyViewedSubMenu(false);
  };

  const handleSearchKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (searchQuery.length < 2) return;
    
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex(prev => (prev < filteredSongs.length - 1 ? prev + 1 : prev));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex(prev => (prev > -1 ? prev - 1 : -1));
    } else if (e.key === 'Enter') {
      if (selectedIndex >= 0 && filteredSongs[selectedIndex]) {
        e.preventDefault();
        handleUserSongSelect(filteredSongs[selectedIndex].id);
      }
    }
  };

  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const scrollToTop = () => {
    scrollContainerRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const scrollToLabel = (label: string) => {
    label = label.toLowerCase();
    const isChorus = label.startsWith('chorus');
    if (isChorus) {
      if (isNaN(parseInt(label.slice(-1)))) 
        label = label + '-0';   // The first and maybe the only one chorus (labeled as "Chorus"), change to 'chorus-0'
      else 
        label = label.slice(0, -2) + '-' + (parseInt(label.slice(-1))-1).toString(); // Chorus 2 -> chorus-1
    }

    const element = document.getElementById(label.replace(/\s+/g, '-'));
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  // Generate labels for all sections for navigation based on the song body. This is used for both 
  // the navigator and the section headers in the lyrics renderer.
  const sectionLabels = useMemo(() => {
    if (!currentSong) return [];
    const blocks = currentSong.body.split(/\n\s*\n\s*/);
    const labels: string[] = [];
    let chorusCount = 1;
    let firstChorusIndex = -1;
    
    const keywords = ['chorus', 'verse', 'bridge', 'coda', 'intro', 'outro', 'pre-chorus', 'instrumental'];

    blocks.forEach(block => {
      const firstLine = block.split('\n')[0].trim().toLowerCase();
      
      if (firstLine.startsWith('{soc}') || firstLine.startsWith('chorus')) {
        if (firstChorusIndex === -1) firstChorusIndex = labels.length;
        labels.push(`Chorus ${chorusCount++}`);
      } else if (keywords.some(k => firstLine.startsWith(k))) {
        // Capitalize the first letter for the label (e.g., "verse 1" -> "Verse 1")
        let cleanLine = firstLine;
        if (cleanLine.endsWith(':')) {
          cleanLine = cleanLine.slice(0, -1);
        }
        labels.push(cleanLine.charAt(0).toUpperCase() + cleanLine.slice(1));
      }
    });
    if (firstChorusIndex !== -1 && chorusCount === 2) {
      labels[firstChorusIndex] = `Chorus`;  // Ensure the only chorus will be labeled simply as "Chorus"
    }
    return labels;
  }, [currentSong?.body]);

  const {
    transpose,
    setTranspose,
    keyInfo,
    CHROMATIC_SCALE,
    setTransposeByKey
  } = useTranspose(currentSong);

  // Handle Setlist Transpose Mode
  useEffect(() => {
    if (!currentSong || !activeSetlist || activeSetlistIndex < 0 || !keyInfo) return;
    
    const mode = user?.settings?.setlistTransposeMode || 'off';
    if (mode === 'off') return;

    const choice = activeSetlist.choices[activeSetlistIndex];
    if (!choice || !choice.key) return;

    const targetKey = choice.key;

    // Ensure we are looking at the correct song (prevents race condition with setlist index)
    if (choice.songId !== currentSong.id) return;

    const currentContextId = `${currentSong.id}-${activeSetlistIndex}`;

    // If transpose is not 0, we are already transposed. Mark as handled.
    if (transpose !== 0) {
      transposeHandledRef.current = currentContextId;
      return;
    }

    // If we've already handled this song instance (e.g. user reset to 0), don't prompt again.
    if (transposeHandledRef.current === currentContextId) return;

    // Mark as handled
    transposeHandledRef.current = currentContextId;

    // Check if we are already in the target key to avoid unnecessary prompts/updates
    const match = targetKey.match(/^([A-G][#b]?)/);
    if (match) {
      let targetRoot = match[1];
      const flatMap: Record<string, string> = { 'Db': 'C#', 'Eb': 'D#', 'Gb': 'F#', 'Ab': 'G#', 'Bb': 'A#' };
      if (flatMap[targetRoot]) targetRoot = flatMap[targetRoot];
      
      const targetIndex = CHROMATIC_SCALE.indexOf(targetRoot);
      if (targetIndex !== -1 && targetIndex === keyInfo.originalIndex) {
        return;
      }
    }

    let timeoutId: ReturnType<typeof setTimeout>;
    if (mode === 'auto') {
      setTransposeByKey(targetKey);
    } else if (mode === 'confirm') {
      // Timeout to ensure UI is stable before alert
      timeoutId = setTimeout(() => {
        // We can check if keys are different before prompting, but setTransposeByKey handles the logic.
        // A simple string check on the choice key vs current key is a decent proxy for "is this different".
        if (window.confirm(`Song: ${currentSong.title}\n\nTranspose to ${targetKey} from ${keyInfo.currentKey}?`)) {
          setTransposeByKey(targetKey);
        }
      }, 100);
    }
    
    return () => clearTimeout(timeoutId);
  }, [currentSong?.id, activeSetlist, activeSetlistIndex, keyInfo, transpose, setTransposeByKey, user?.settings?.setlistTransposeMode, CHROMATIC_SCALE]);

  // Sync theme
  const { setTheme } = useTheme();

  // Sync User Settings Theme with ThemeProvider
  useEffect(() => {
    if (user?.settings.theme) {
      setTheme(user.settings.theme);
    }
  }, [user?.settings.theme, setTheme]);

  const handleSaveSong = async (songData: Partial<Song>, keepOpen: boolean = false) => {
    if (!user) {
      console.error("User not authenticated. Cannot save song.");
      return;
    }
    // Use existing ownerId if available (editing), otherwise assign to current user (creating)
    const ownerId = songData.ownerId || user.id;
    const savedSong = await saveSong({ ...songData, ownerId });

    if (keepOpen) {
      // If we are keeping the editor open, we need to update the song being edited,
      // especially if it was a new song that now has an ID.
      setSongToEdit(savedSong);
    } else {
      setView('SONG_VIEW');
      setSongToEdit(undefined); // Clean up state on exit
    }
  };

  const handleArchiveSetlist = async (setlistId: string) => {
    const setlistToArchive = setlists.find(s => s.id === setlistId);
    if (!setlistToArchive) return;

    let confirmMessage = `Are you sure you want to archive the setlist "${setlistToArchive.name}"?`;

    if (activeSetlist && activeSetlist.id === setlistId) {
      confirmMessage += `\n\nWARNING: This is the currently active setlist. Archiving it will exit the current session.`;
    }

    if (window.confirm(confirmMessage)) {
      if (activeSetlist && activeSetlist.id === setlistId) {
        exitSetlist();
      }
      await saveSetlist({ ...setlistToArchive, isArchived: true });
    }
  };

  const performArchiveSong = async (songToArchive: Song) => {
    if (!songToArchive) return;

    const setlistsContainingSong = setlists.filter(setlist =>
      !setlist.isArchived && setlist.choices.some(choice => choice.songId === songToArchive.id)
    );

    let confirmMessage = `Are you sure you want to archive the song "${songToArchive.title}"?`;

    if (setlistsContainingSong.length > 0) {
      const setlistNames = setlistsContainingSong.map(s => `"${s.name}"`).join(', ');
      confirmMessage += `\n\nThis song will also be removed from ${setlistsContainingSong.length} active setlist(s):\n${setlistNames}`;
    }

    if (window.confirm(confirmMessage)) {
      // 1. Archive the song by setting the flag
      await saveSong({ ...songToArchive, isArchived: true });

      // 2. Remove the song from any active setlists it was in
      const updatePromises = setlistsContainingSong.map(setlist => {
        const newChoices = setlist.choices.filter(choice => choice.songId !== songToArchive.id);
        return saveSetlist({ ...setlist, choices: newChoices });
      });
      await Promise.all(updatePromises);

      // 3. If the archived song was the current song, navigate away
      if (currentSong?.id === songToArchive.id) {
        handleNavigation('SONG_VIEW');
      }
    }
  };

  const handleArchiveSong = async () => {
    if (currentSong) await performArchiveSong(currentSong);
  };

  const handleSync = async () => {
    if (isSyncing) return;
    setIsSyncing(true);
    try {
      await dbService.refreshCache();
      await Promise.all([refreshSongs(), refreshSetlists()]);
      const now = Date.now();
      setLastSyncTime(now);
      localStorage.setItem('cloudsong_last_synced', now.toString());
      setShowSyncSuccess(true);
    } catch (error) {
      console.error("Sync error:", error);
      alert("Sync failed. Please check your connection and try again.");
    } finally {
      setIsSyncing(false);
    }
  };

  const handlePlaySetlist = async (setlist: SetList) => {
    // The useEffect watching activeSetlist will handle adding to cache.
    await playSetlist(setlist);
    setView('SONG_VIEW');
    setMenuOpen(false);
    setShowRecentlyPlayedSetlistsSubMenu(false);
  };

  const closeCreateSetlistModal = () => {
    setShowCreateSetlistModal(false);
    setSongsForSetlist([]); // Clear the temporary songs
    setNewSetlistName('');
    setEditSetlistImmediately(true); // Reset to default
  };

  const handleCreateSetlistFromSearch = async () => {
    if (!newSetlistName.trim() || !user) return;

    const newId = Date.now().toString();
    const newSetlist: SetList = {
      id: newId,
      name: newSetlistName,
      choices: songsForSetlist.map(s => ({
        songId: s.id,
        key: s.key,
        tempo: s.tempo,
        style: '',
        singer: ''
      })),
      createdAt: Date.now(),
      updatedAt: Date.now(),
      ownerId: user.id,
      lastUsedAt: 0
    };

    await saveSetlist(newSetlist);
    
    closeCreateSetlistModal();
    
    if (editSetlistImmediately) {
      setTargetSetlistId(newId);
      setView('SETLIST_MANAGER');
    } else {
      setTargetSetlistId(null);
    } 
  };

  const isSearchPinned = useMemo(() => {
    // It's pinned if a pinned query exists and it matches the current search query.
    // It should not be considered "pinned" if the query is empty.
    return pinnedSearchQuery && pinnedSearchQuery === searchQuery;
  }, [pinnedSearchQuery, searchQuery]);

  const handlePinToggle = () => {
    if (isSearchPinned) {
      // If the current search is already pinned, unpin it.
      setPinnedSearchQuery('');
    } else if (searchQuery) {
      // Otherwise, pin the current search query.
      setPinnedSearchQuery(searchQuery);
    }
  };

  const handleSearchActiveChange = (isActive: boolean) => {
    if (isActive && pinnedSearchQuery) {
      setSearchQuery(pinnedSearchQuery);
    }
    setIsHeaderSearchActive(isActive);
  };

  const handleEditCurrentSong = () => {
    if (!currentSong) return;

    if (transpose !== 0 && keyInfo) {
      const confirmMsg = `You are viewing this song in ${keyInfo.currentKey} (Transposed).\n\nDo you want to edit the song using the transposed chords?\n(Cancel will open the original key: ${currentSong.key})`;
      if (window.confirm(confirmMsg)) {
        const shouldUseFlats = getShouldUseFlats(currentSong.key, transpose);
        const newBody = currentSong.body.replace(/\[(.*?)\]/g, (_match, chord) => {
          return `[${transposeChord(chord, transpose, shouldUseFlats)}]`;
        });

        const transposedSong = {
          ...currentSong,
          key: keyInfo.currentKey,
          body: newBody
        };

        handleNavigation('SONG_FORM', () => setSongToEdit(transposedSong));
        return;
      }
    }
    handleNavigation('SONG_FORM', () => setSongToEdit(currentSong));
  };

  if (!user) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-600 to-indigo-900 flex items-center justify-center p-4">
        <div className="bg-white p-8 rounded-3xl shadow-2xl w-full max-w-md text-center">
          <div className="mb-6 flex justify-center">
            <img src="/icons/icon-192x192.png" alt="CloudSongBook Logo" className="w-24 h-24 rounded-2xl shadow-lg" />
          </div>
          <h1 className="text-4xl font-extrabold text-gray-900 mb-2">CloudSongBook</h1>
          <p className="text-gray-500 mb-8">Your digital stage companion</p>
          <div className="space-y-4">
            {!showEmailForm ? (
              <>
                <button 
                  onClick={handleGoogleLogin}
                  className="w-full flex items-center justify-center space-x-3 bg-white border border-gray-300 py-3 rounded-xl hover:bg-gray-50 transition-all font-semibold"
                >
                  <i className="fa-brands fa-google text-red-500"></i>
                  <span>Continue with Google</span>
                </button>
                <button 
                  onClick={() => setShowEmailForm(true)}
                  className="w-full flex items-center justify-center space-x-3 bg-blue-600 text-white py-3 rounded-xl hover:bg-blue-700 shadow-lg shadow-blue-200 transition-all font-semibold"
                >
                  <i className="fa-solid fa-envelope"></i>
                  <span>Login with Email</span>
                </button>
              </>
            ) : (
              <form onSubmit={handleEmailAuth} className="space-y-4 text-left animate-fadeIn">
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Email</label>
                  <input 
                    type="email" 
                    required
                    className="w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm focus:ring-blue-500 focus:border-blue-500"
                    placeholder="name@example.com"
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                  />
                </div>
                <div>
                  <label className="block text-sm font-bold text-gray-700 mb-1">Password</label>
                  <input 
                    type="password" 
                    required
                    className="w-full rounded-lg border-gray-300 bg-gray-50 p-2.5 text-sm focus:ring-blue-500 focus:border-blue-500"
                    placeholder="••••••••"
                    value={password}
                    onChange={e => setPassword(e.target.value)}
                  />
                  {!isSignUp && (
                    <div className="flex justify-end mt-1">
                      <button 
                        type="button"
                        onClick={handlePasswordReset}
                        className="text-xs text-blue-600 hover:text-blue-800 font-semibold"
                      >
                        Forgot Password?
                      </button>
                    </div>
                  )}
                </div>
                
                {authError && (
                  <p className="text-red-500 text-sm font-medium">{authError}</p>
                )}
                {resetSent && (
                  <p className="text-green-600 text-sm font-medium">Password reset email sent! Check your inbox.</p>
                )}
                {verificationSent && (
                  <p className="text-green-600 text-sm font-medium">Account created! Verification email sent.</p>
                )}

                <button 
                  type="submit"
                  className="w-full bg-blue-600 text-white py-3 rounded-xl hover:bg-blue-700 font-bold shadow-lg shadow-blue-200 transition-all"
                >
                  {isSignUp ? 'Sign Up' : 'Sign In'}
                </button>

                <div className="flex justify-between items-center text-sm pt-2">
                  <button type="button" onClick={() => setShowEmailForm(false)} className="text-gray-500 hover:text-gray-700">Back</button>
                  <button type="button" onClick={() => setIsSignUp(!isSignUp)} className="text-blue-600 hover:text-blue-800 font-semibold">
                    {isSignUp ? 'Switch to Login' : 'Create an account'}
                  </button>
                </div>
              </form>
            )}
            <div className="pt-6 border-t border-gray-100 flex justify-between text-xs text-gray-400">
              <a href="#" className="hover:text-blue-600">Privacy Policy</a>
              <a href="#" className="hover:text-blue-600">Terms of Service</a>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Display a loading indicator after login while initial data is being fetched.
  // `isRouteHandled` is set to true only after songs/setlists are loaded for the first time.
  if (user && !isRouteHandled) {
    return (
      <div className="h-screen flex flex-col bg-gray-50 dark:bg-gray-900">
        <Header title="CloudSongBook" searchQuery="" setSearchQuery={() => {}} onMenuClick={() => {}} />
        <main className="flex-1 flex items-center justify-center text-center">
          <div>
            <i className="fa-solid fa-spinner fa-spin text-4xl text-blue-500 mb-4"></i>
            <p className="text-lg font-semibold text-gray-700 dark:text-gray-300">Loading your songbook...</p>
            <p className="text-sm text-gray-500 dark:text-gray-400">Fetching songs and setlists...</p>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="h-screen overflow-hidden flex flex-col">
      <div className="h-full flex flex-col bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-200">
      {/* Header */}
      <Header
        title={currentSong?.title || "CloudSongBook"}
        searchQuery={searchQuery}
        setSearchQuery={setSearchQuery}
        onMenuClick={() => setMenuOpen(true)}
        isSearchActive={isHeaderSearchActive}
        onSearchActiveChange={handleSearchActiveChange}
        onKeyDown={handleSearchKeyDown}
        menuOpen={menuOpen}
        rightContent={
          <div className={`hidden md:flex items-center space-x-2 transition-all duration-300 ${view !== 'SONG_VIEW' ? 'blur-sm opacity-50 pointer-events-none' : ''}`}>
            {currentSong?.key && keyInfo && (
              <div 
                className={`flex items-center rounded-lg p-1 border select-none transition-all duration-300 ${
                  transpose !== 0 
                    ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-300 dark:border-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.4)]' 
                    : 'bg-gray-100 dark:bg-gray-700 border-gray-200 dark:border-gray-600'
                }`}
                onDoubleClick={() => setTranspose(0)}
                title={transpose !== 0 ? "Key changed. Double-click to reset." : "Original Key"}
              >
                <span className={`text-xs font-bold ml-2 mr-1 ${transpose !== 0 ? 'text-blue-700 dark:text-blue-300' : 'text-gray-500 dark:text-gray-300'}`}>Key:</span>
                <div className="relative">
                  <select
                    aria-label="Transpose Key"
                    className={`appearance-none bg-transparent font-bold text-sm py-1 pl-2 pr-6 cursor-pointer focus:outline-none ${transpose !== 0 ? 'text-blue-900 dark:text-blue-100' : 'text-gray-900 dark:text-white'}`}
                    value={keyInfo.currentKey}
                    onChange={(e) => {
                      setTransposeByKey(e.target.value);
                    }}
                  >
                    {CHROMATIC_SCALE.map((note) => (
                      <option key={note} value={note + keyInfo.suffix} className="bg-white dark:bg-gray-800 text-gray-900 dark:text-white">
                        {getKeyLabel(note, keyInfo.suffix)}
                      </option>
                    ))}
                  </select>
                </div>
                
                <div className={`flex flex-col ml-1 border-l pl-1 ${transpose !== 0 ? 'border-blue-200 dark:border-blue-700' : 'border-gray-300 dark:border-gray-600'}`}>
                  <button aria-label="Up a semitone"
                    onClick={() => setTranspose(t => t + 1)} className={`h-3 flex items-center justify-center rounded px-1 ${transpose !== 0 ? 'text-blue-600 dark:text-blue-300 hover:bg-blue-200 dark:hover:bg-blue-800' : 'text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                    <i className="fa-solid fa-caret-up text-[10px]"></i>
                  </button>
                  <button aria-label="Down a semitone"
                    onClick={() => setTranspose(t => t - 1)} className={`h-3 flex items-center justify-center rounded px-1 ${transpose !== 0 ? 'text-blue-600 dark:text-blue-300 hover:bg-blue-200 dark:hover:bg-blue-800' : 'text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-200 dark:hover:bg-gray-600'}`}>
                    <i className="fa-solid fa-caret-down text-[10px]"></i>
                  </button>
                </div>

                {transpose !== 0 && (
                  <button
                    onClick={() => setTranspose(0)}
                    className="ml-2 mr-1 w-5 h-5 flex items-center justify-center rounded-full bg-blue-200 dark:bg-blue-800 text-blue-700 dark:text-blue-200 hover:bg-blue-300 dark:hover:bg-blue-700 transition-colors animate-in fade-in zoom-in duration-200"
                    title="Reset to Original Key"
                  >
                    <i className="fa-solid fa-rotate-left text-[10px]"></i>
                  </button>
                )}
              </div>
            )}

            <div 
              className="flex items-center bg-gray-100 dark:bg-gray-700 rounded-lg p-1 border border-gray-200 dark:border-gray-600 ml-2 select-none"
              onDoubleClick={() => handleUpdateSettings({ fontSize: 18 })}
              title="Double-click to reset zoom"
            >
              <span className="text-xs font-bold text-gray-500 dark:text-gray-300 ml-2 mr-1">Zoom:</span>
              <div className="relative">
                <select
                  aria-label="Font Size"
                  className="appearance-none bg-transparent font-bold text-gray-900 dark:text-white text-sm py-1 pl-2 pr-6 cursor-pointer focus:outline-none"
                  value={user.settings.fontSize}
                  onChange={(e) => handleUpdateSettings({ fontSize: parseInt(e.target.value) })}
                >
                  {[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 36, 40, 48].map((size) => (
                    <option key={size} value={size} className="bg-white dark:bg-gray-800 text-gray-900 dark:text-white">{size}</option>
                  ))}
                </select>
              </div>
              
              <div className="flex flex-col ml-1 border-l border-gray-300 dark:border-gray-600 pl-1">
                <button 
                  aria-label="Increase Font Size"
                  onClick={() => handleUpdateSettings({ fontSize: Math.min(48, user.settings.fontSize + 2) })}
                  className="h-3 flex items-center justify-center text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-200 dark:hover:bg-gray-600 rounded px-1">
                  <i className="fa-solid fa-caret-up text-[10px]"></i>
                </button>
                <button 
                  aria-label="Decrease Font Size"
                  onClick={() => handleUpdateSettings({ fontSize: Math.max(12, user.settings.fontSize - 2) })} className="h-3 flex items-center justify-center text-gray-500 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-200 dark:hover:bg-gray-600 rounded px-1">
                  <i className="fa-solid fa-caret-down text-[10px]"></i>
                </button>
              </div>
            </div>
          </div>
        }
      />

      {/* Main Content */}
      <main 
        ref={scrollContainerRef}
        className="flex-1 overflow-y-auto relative"
        onMouseDown={(e) => {
          // Prevent closing search when clicking on scrollbar or empty space in search results
          if (isHeaderSearchActive && searchQuery.length >= 2) {
            e.nativeEvent.stopImmediatePropagation();
          }
        }}
      >
        {searchQuery.length >= 2 ? (
          <>
            <div className="px-4 py-2 flex justify-between items-center gap-2 bg-gray-50 dark:bg-gray-900 sticky top-0 z-10 border-b border-gray-100 dark:border-gray-800">
              <button
                onClick={handlePinToggle}
                title={isSearchPinned ? "Unpin this search" : "Pin these search results"}
                className={`flex items-center gap-1.5 text-xs font-semibold px-3 py-1 rounded-full border transition-colors ${
                  isSearchPinned
                    ? 'bg-yellow-100 text-yellow-800 border-yellow-300 dark:bg-yellow-900/50 dark:text-yellow-300 dark:border-yellow-700'
                    : 'bg-white text-gray-600 border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700'
                }`}
              >
                <i className={`fa-solid fa-thumbtack transition-transform ${isSearchPinned ? 'rotate-0' : 'rotate-45'}`}></i>
                <span>{isSearchPinned ? 'Pinned' : 'Pin'}</span>
              </button>
              <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-gray-500 dark:text-gray-400">Sort by:</span>
              <button 
                onClick={() => handleSortChange('dateAdded')}
                className={`text-xs font-semibold px-3 py-1 rounded-full border transition-colors flex items-center gap-1.5 ${sortOrder === 'dateAdded' ? 'bg-blue-100 text-blue-700 border-blue-300 dark:bg-blue-900/50 dark:text-blue-300 dark:border-blue-700' : 'bg-white text-gray-600 border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700'}`}
              >
                Date Added
                {sortOrder === 'dateAdded' && <i className={`fa-solid ${sortDirection === 'asc' ? 'fa-arrow-up-short-wide' : 'fa-arrow-down-wide-short'}`}></i>}
              </button>
              <button 
                onClick={() => handleSortChange('relevance')}
                className={`text-xs font-semibold px-3 py-1 rounded-full border transition-colors flex items-center gap-1.5 ${sortOrder === 'relevance' ? 'bg-blue-100 text-blue-700 border-blue-300 dark:bg-blue-900/50 dark:text-blue-300 dark:border-blue-700' : 'bg-white text-gray-600 border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700'}`}
              >
                Relevance
                {sortOrder === 'relevance' && <i className={`fa-solid ${sortDirection === 'asc' ? 'fa-arrow-up-short-wide' : 'fa-arrow-down-wide-short'}`}></i>}
              </button>
              <button 
                onClick={() => handleSortChange('lastUsed')}
                className={`text-xs font-semibold px-3 py-1 rounded-full border transition-colors flex items-center gap-1.5 ${sortOrder === 'lastUsed' ? 'bg-blue-100 text-blue-700 border-blue-300 dark:bg-blue-900/50 dark:text-blue-300 dark:border-blue-700' : 'bg-white text-gray-600 border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700'}`}
              >
                Last Used
                {sortOrder === 'lastUsed' && <i className={`fa-solid ${sortDirection === 'asc' ? 'fa-arrow-up-short-wide' : 'fa-arrow-down-wide-short'}`}></i>}
              </button>
              <button 
                onClick={() => handleSortChange('alphabetic')}
                className={`text-xs font-semibold px-3 py-1 rounded-full border transition-colors flex items-center gap-1.5 ${sortOrder === 'alphabetic' ? 'bg-blue-100 text-blue-700 border-blue-300 dark:bg-blue-900/50 dark:text-blue-300 dark:border-blue-700' : 'bg-white text-gray-600 border-gray-300 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700'}`}
              >
                Alphabetic
                {sortOrder === 'alphabetic' && <i className={`fa-solid ${sortDirection === 'asc' ? 'fa-arrow-down-a-z' : 'fa-arrow-down-z-a'}`}></i>}
              </button>
              
              {/* Create Setlist from Search Button (Admin/Premium only) */}
              {(user.role === UserRole.ADMIN || user.role === UserRole.PREMIUM) && filteredSongs.length > 0 && (
                <button 
                  onClick={() => {
                    setSongsForSetlist(filteredSongs);
                    setNewSetlistName(`Search Results - ${new Date().toLocaleDateString()}`);
                    setShowCreateSetlistModal(true);
                  }}
                  className="ml-2 flex items-center gap-1.5 text-xs font-semibold px-3 py-1 rounded-full border bg-green-100 text-green-700 border-green-300 dark:bg-green-900/50 dark:text-green-300 dark:border-green-700 hover:bg-green-200 dark:hover:bg-green-800/50 transition-colors"
                  title="Create Setlist from these results"
                >
                  <i className="fa-solid fa-file-circle-plus"></i>
                  <span>Make Setlist</span>
                </button>
              )}
              </div>
            </div>
            <SongList 
              songs={filteredSongs} 
              searchQuery={searchQuery}
              selectedIndex={selectedIndex}
              onSongClick={(song) => handleUserSongSelect(song.id)}
              highlightSearch={user?.settings.highlightSearch ?? false}
            />
          </>
        ) : (
          <>
        {view === 'SONG_VIEW' && currentSong && (
          <>
            <SongViewer 
              song={currentSong} 
              settings={user.settings} 
              onUpdateSettings={handleUpdateSettings}
              transpose={transpose}
              onTranspose={setTranspose}
              activeSetlist={activeSetlist}
              activeSetlistIndex={activeSetlistIndex}
              onNextSong={() => navigateSetlist('next')}
              onPrevSong={() => navigateSetlist('prev')}
              onSetlistJump={(idx) => navigateSetlist(idx)}
              onExitSetlist={exitSetlist}
              allSongs={allSongs}
              onUpdateSong={handleSaveSong}
              localShowChords={localShowChords}
              onSetLocalShowChords={setLocalShowChords}
              user={user}
              setlists={setlists}
              onSaveSetlist={saveSetlist}
            />
            <SongNavigator 
              sectionLabels={sectionLabels}
              onScrollToTop={scrollToTop}
              onScrollToLabel={scrollToLabel}
            />
          </>
        )}
        {view === 'SONG_FORM' && (
          <SongForm 
            song={songToEdit}
            onSave={handleSaveSong}
            onCancel={() => {
              setView('SONG_VIEW');
              setSongToEdit(undefined);
            }} 
          />
        )}
        {view === 'RECENT_SONGS' && (
          <RecentSongsView 
            songs={recentSongs.filter(s => !s.isArchived)}
            onSelectSong={handleUserSongSelect}
            onEditSong={(song) => {
              setSongToEdit(song);
              setView('SONG_FORM');
            }}
            onArchiveSong={performArchiveSong}
            onBack={() => setView('SONG_VIEW')}
          />
        )}
        {view === 'SETLIST_MANAGER' && (
          <SetlistManager
            user={user}
            setlists={setlists}
            allSongs={allSongs.filter(s => !s.isArchived)}
            currentSong={currentSong ?? undefined}
            onSave={saveSetlist}
            onArchive={handleArchiveSetlist}
            onPlay={handlePlaySetlist}
            onClose={() => {
              // If we came from the admin dashboard (indicated by the filter), go back there.
              if (adminSetlistFilter) {
                setView('ADMIN_DASHBOARD');
              } else { // This is the default behavior when closing SetlistManager not from admin dashboard
                setView('SONG_VIEW');
              }
              setTargetSetlistId(null);
              setAdminSetlistFilter('');
            }}
            onDirtyChange={setHasUnsavedChanges}
            initialEditingId={targetSetlistId}
            initialSearchQuery={adminSetlistFilter}
          />
        )}
        {view === 'SETTINGS' && (
          <SettingsView 
            user={user}
            onSave={(newSettings) => {
              handleUpdateSettings(newSettings);
              setView('SONG_VIEW');
            }}
            onCancel={() => setView('SONG_VIEW')}
          />
        )}
        {view === 'ADMIN_DASHBOARD' && user && (
          <AdminDashboard
            currentUser={user}
            onBack={() => handleNavigation('SONG_VIEW')}
            allSongs={allSongs}
            allSetlists={setlists}
            onNavigate={handleAdminNavigate}
            onSaveSong={saveSong}
            onSaveSetlist={saveSetlist}
            onDeleteSong={deleteSpecificSong}
            onDeleteSetlist={deleteSetlist}
          />
        )}
          </>
        )}
      </main>

      {/* Burger Menu Sidebar */}
      {menuOpen && (
        <>
          <div
            className="fixed inset-0 bg-black/40 backdrop-blur-sm z-40 transition-opacity"
            onClick={() => {
              setMenuOpen(false);
              setShowRecentlyViewedSubMenu(false);
              setShowRecentlyPlayedSetlistsSubMenu(false);
            }}
          ></div>
          <div className="fixed inset-y-0 left-0 w-80 z-50 overflow-hidden">
            {/* Main Menu Panel */}
            <aside className={`absolute inset-y-0 left-0 w-80 bg-white dark:bg-gray-800 shadow-2xl transform transition-transform duration-300 ease-in-out overflow-y-auto ${(showRecentlyViewedSubMenu || showRecentlyPlayedSetlistsSubMenu) ? '-translate-x-full' : 'translate-x-0'}`}>
            <div className="p-6 border-b border-gray-100 dark:border-gray-700 flex items-center space-x-4">
              <div className="w-12 h-12 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center text-blue-600 dark:text-blue-300 text-xl font-bold">
                {user.name.charAt(0)}
              </div>
              <div>
                <p className="font-bold text-gray-900 dark:text-gray-100">{user.name}</p>
                <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-semibold">{user.role} Member</p>
              </div>
            </div>

            <nav className="p-4 space-y-1">
              <p className="px-4 py-2 text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider">Song Management</p>
              <button 
                onClick={() => {
                  if (!user) return;
                  setRecentlyViewed(dbService.getRecentCache(user.id).slice(0, 20));
                  setShowRecentlyViewedSubMenu(true);
                }}
                className="w-full flex items-center justify-between px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <div className="flex items-center space-x-3">
                  <i className="fa-solid fa-eye w-6"></i>
                  <span className="font-medium">Recently Viewed</span>
                </div>
                <i className="fa-solid fa-chevron-right text-gray-400"></i>
              </button>
              <button 
                onClick={() => handleNavigation('RECENT_SONGS')}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <i className="fa-solid fa-layer-group w-6"></i>
                <span className="font-medium">Recent 50 Additions</span>
              </button>
              {/* "Add New Song" for Admin and Premium */}
              {(user.role === UserRole.ADMIN || user.role === UserRole.PREMIUM) && (
                <button 
                  onClick={() => handleNavigation('SONG_FORM', () => setSongToEdit(undefined))}
                  className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
                >
                  <i className="fa-solid fa-plus w-6"></i>
                  <span className="font-medium">Add New Song</span>
                </button>
              )}

              {/* "Edit Current Song" for Admin (always) or Premium (if owner) */}
              {(user.role === UserRole.ADMIN || (user.role === UserRole.PREMIUM && currentSong?.ownerId === user.id)) && (
                <button 
                  onClick={handleEditCurrentSong}
                  disabled={!currentSong}
                  className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <i className="fa-solid fa-pen-to-square w-6"></i>
                  <span className="font-medium">Edit Current Song</span>
                </button>
              )}

              {/* "Delete Current Song" for Admin (always) or Premium (if owner) */}
              {(user.role === UserRole.ADMIN || (user.role === UserRole.PREMIUM && currentSong?.ownerId === user.id)) && (
                <button 
                  onClick={() => { handleArchiveSong(); setMenuOpen(false); }}
                  disabled={!currentSong}
                  className="w-full flex items-center space-x-3 px-4 py-3 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <i className="fa-solid fa-archive w-6"></i>
                  <span className="font-medium">Archive Current Song</span>
                </button>
              )}

              <div className="my-4 border-t border-gray-100 dark:border-gray-700" />
              
              <p className="px-4 py-2 text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider">Playlists</p>
              <button 
                onClick={() => handleNavigation('SETLIST_MANAGER')}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <i className="fa-solid fa-list-ul w-6"></i>
                <span className="font-medium">All Setlists</span>
              </button>
              <button 
                onClick={() => {
                  if (!user) return;
                  setRecentlyPlayedSetlists(dbService.getRecentSetlistsCache(user.id));
                  setShowRecentlyPlayedSetlistsSubMenu(true);
                }}
                className="w-full flex items-center justify-between px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <div className="flex items-center space-x-3">
                  <i className="fa-solid fa-history w-6"></i>
                  <span className="font-medium">Recently Played</span>
                </div>
                <i className="fa-solid fa-chevron-right text-gray-400"></i>
              </button>
              {activeSetlist && (
                <button 
                  onClick={() => { exitSetlist(); setMenuOpen(false); }} // Exit setlist doesn't change view, just state
                  className="w-full flex items-center space-x-3 px-4 py-3 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-colors"
                >
                  <i className="fa-solid fa-circle-stop w-6"></i>
                  <span className="font-medium">Exit Current Set</span>
                </button>
              )}

              <div className="my-4 border-t border-gray-100 dark:border-gray-700" />

              {user.role === UserRole.ADMIN && (
                <button 
                  onClick={() => handleNavigation('ADMIN_DASHBOARD')}
                  className="w-full flex items-center space-x-3 px-4 py-3 text-purple-600 dark:text-purple-400 hover:bg-purple-50 dark:hover:bg-purple-900/20 rounded-xl transition-colors"
                >
                  <i className="fa-solid fa-users-gear w-6"></i>
                  <span className="font-medium">Admin Dashboard</span>
                </button>
              )}

              <p className="px-4 py-2 text-xs font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wider">Account</p>
              <button 
                onClick={() => handleUpdateSettings({ theme: user.settings.theme === 'dark' ? 'light' : 'dark' })}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <i className={`fa-solid ${user.settings.theme === 'dark' ? 'fa-sun' : 'fa-moon'} w-6`}></i>
                <span className="font-medium">{user.settings.theme === 'dark' ? 'To Light Mode' : 'To Dark Mode'}</span>
              </button>
              <button 
                onClick={handleSync}
                disabled={isSyncing}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors disabled:opacity-50"
              >
                <i className={`fa-solid fa-rotate w-6 ${isSyncing ? 'fa-spin' : ''}`}></i>
                <span className="font-medium">{isSyncing ? 'Syncing...' : 'Sync Data'}</span>
              </button>
              {lastSyncTime && (
                <div className="flex items-center space-x-3 px-4 -mt-2 mb-2">
                  <div className="w-6 shrink-0" aria-hidden="true" />
                  <p className="text-[10px] text-gray-400 dark:text-gray-500">
                    Last synced: <TimeAgo timestamp={lastSyncTime} />
                  </p>
                </div>
              )}
              <button 
                onClick={() => handleNavigation('SETTINGS')}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 rounded-xl transition-colors"
              >
                <i className="fa-solid fa-user-gear w-6"></i>
                <span className="font-medium">Profile & Settings</span>
              </button>
              <button 
                onClick={() => {
                  if (hasUnsavedChanges && !window.confirm('You have unsaved changes. Are you sure you want to discard them?')) return;
                  handleLogout();
                }}
                className="w-full flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-red-50 dark:hover:bg-red-900/20 hover:text-red-600 dark:hover:text-red-400 rounded-xl transition-colors"
              >
                <i className="fa-solid fa-right-from-bracket w-6"></i>
                <span className="font-medium">Logout</span>
              </button>
            </nav>
            </aside>

            {/* Recently Viewed Sub-Menu Panel */}
            <div className={`absolute inset-y-0 left-0 w-80 bg-white dark:bg-gray-800 shadow-2xl transform transition-transform duration-300 ease-in-out ${showRecentlyViewedSubMenu ? 'translate-x-0' : 'translate-x-full'}`}>
              <div className="p-2 border-b border-gray-100 dark:border-gray-700">
                <button 
                  onClick={() => setShowRecentlyViewedSubMenu(false)}
                  className="w-full flex items-center space-x-3 px-2 py-2 text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                >
                  <i className="fa-solid fa-chevron-left w-6"></i>
                  <span className="font-bold">Recently Viewed</span>
                </button>
              </div>
              <div className="overflow-y-auto h-full pb-12">
                {recentlyViewed.length > 0 ? recentlyViewed.map(song => (
                  <button 
                    key={song.id}
                    onClick={() => handleUserSongSelect(song.id)}
                    className="w-full text-left flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 transition-colors"
                  >
                    <div className="truncate">
                      <p className="font-medium truncate">{song.title}</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400 truncate">{song.authors}</p>
                    </div>
                  </button>
                )) : (
                  <p className="px-4 py-8 text-center text-sm text-gray-500 dark:text-gray-400">No recently viewed songs.</p>
                )}
              </div>
            </div>

            {/* Recently Played Setlists Sub-Menu Panel */}
            <div className={`absolute inset-y-0 left-0 w-80 bg-white dark:bg-gray-800 shadow-2xl transform transition-transform duration-300 ease-in-out ${showRecentlyPlayedSetlistsSubMenu ? 'translate-x-0' : 'translate-x-full'}`}>
              <div className="p-2 border-b border-gray-100 dark:border-gray-700">
                <button 
                  onClick={() => setShowRecentlyPlayedSetlistsSubMenu(false)}
                  className="w-full flex items-center space-x-3 px-2 py-2 text-gray-700 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                >
                  <i className="fa-solid fa-chevron-left w-6"></i>
                  <span className="font-bold">Recently Played</span>
                </button>
              </div>
              <div className="overflow-y-auto h-full pb-12">
                {recentlyPlayedSetlists.length > 0 ? recentlyPlayedSetlists.map(setlist => (
                  <button 
                    key={setlist.id}
                    onClick={() => handlePlaySetlist(setlist)}
                    className="w-full text-left flex items-center space-x-3 px-4 py-3 text-gray-700 dark:text-gray-200 hover:bg-blue-50 dark:hover:bg-gray-700 transition-colors"
                  >
                    <div className="truncate">
                      <p className="font-medium truncate">{setlist.name}</p>
                      <p className="text-xs text-gray-500 dark:text-gray-400 truncate">{setlist.choices.length} songs</p>
                    </div>
                  </button>
                )) : (
                  <p className="px-4 py-8 text-center text-sm text-gray-500 dark:text-gray-400">No recently played setlists.</p>
                )}
              </div>
            </div>
          </div>
        </>
      )}

      {/* PWA Update Prompt */}
      {needRefresh && (
        <UpdatePrompt 
          onUpdate={() => updateServiceWorker()}
          onDismiss={() => setNeedRefresh(false)}
        />
      )}

      {/* PWA Offline Ready Toast */}
      {offlineReady && (
        <OfflineReadyToast onDismiss={() => setOfflineReady(false)} />
      )}

      {/* Sync Success Toast */}
      {showSyncSuccess && (
        <div className="fixed bottom-4 left-1/2 -translate-x-1/2 z-50 bg-gray-800 dark:bg-green-600 text-white rounded-xl shadow-2xl p-4 max-w-sm animate-slideInUp flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <i className="fa-solid fa-circle-check text-xl"></i>
            <p className="text-sm font-bold">Data synced successfully!</p>
          </div>
          <button title="Dismiss" onClick={() => setShowSyncSuccess(false)} className="text-white/70 hover:text-white transition-colors">
            <i className="fa-solid fa-xmark"></i>
          </button>
        </div>
      )}

      </div>

      {/* Create Setlist Modal */}
      {showCreateSetlistModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fadeIn">
          <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md shadow-2xl border border-gray-200 dark:border-gray-700">
            <h3 className="text-xl font-bold mb-4 text-gray-900 dark:text-white">Create Setlist from Search</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
              Create a new setlist containing all {songsForSetlist.length} songs from your current search results.
            </p>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">Setlist Name</label>
                <input 
                  value={newSetlistName}
                  onChange={e => setNewSetlistName(e.target.value)}
                  placeholder="e.g., Sunday Service"
                  className="w-full rounded-xl border-gray-200 dark:border-gray-600 bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white shadow-sm border p-3 focus:ring-2 focus:ring-blue-500 transition-all"
                  autoFocus
                />
              </div>
              
              <label className="flex items-center space-x-3 cursor-pointer">
                <input 
                  type="checkbox" 
                  checked={editSetlistImmediately}
                  onChange={e => setEditSetlistImmediately(e.target.checked)}
                  className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500 border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700"
                />
                <span className="text-sm font-medium text-gray-700 dark:text-gray-300">Open in Setlist Editor immediately</span>
              </label>
            </div>

            <div className="mt-8 flex justify-end gap-3">
              <button 
                onClick={closeCreateSetlistModal}
                className="px-4 py-2 text-gray-600 dark:text-gray-300 font-bold border border-gray-300 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleCreateSetlistFromSearch}
                disabled={!newSetlistName.trim()}
                className="px-6 py-2 bg-blue-600 text-white rounded-lg font-bold hover:bg-blue-700 shadow-lg shadow-blue-200 dark:shadow-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Create Setlist
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default App;
